name: First workflow

on:
  push:
    branches:
      - 'feature/devOps-develop'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy locally
        run: |
          cd /var/www/html/

          # If repo already exists → pull latest changes
          if [ -d "StudentBook-mini--on-GA" ]; then
            cd StudentBook-mini--on-GA
            git pull origin feature/devOps-develop
          else
            git clone https://github.com/Deepika-M-git/StudentBook-mini--on-GA.git
          fi

          pwd
          ls -la
          cd StudentBook-mini--on-GA/client
          rm -rf node_modules package-lock.json
          npm install
          npm run build
          
          
